In [7]:
import numpy as np
import pandas as pd

In [8]:
data = pd.read_excel("4주차 과제 TW raw data_와랑이멘토.xlsx",skiprows=2,usecols="F,G, K,L")
data

     Entity  wafer  Therma wave    Range
0    IMP#02      4     889.0000   0.0000
1    IMP#02      1     879.0000  10.0000
2    IMP#02     10     887.0000   8.0000
3    IMP#02     10     894.0000   7.0000
4    IMP#02     10     887.0000   7.0000
..      ...    ...          ...      ...
107  IMP#02      4     888.3782  16.6218
108  IMP#02      4     910.0000  21.6218
109  IMP#01     12     909.0000   1.0000
110  IMP#01     10     923.0000  14.0000
111  IMP#01     15     918.0000   5.0000

[112 rows x 4 columns]

In [94]:
#print(type(data["Therma wave"]))
a = pd.Series(data["Therma wave"])
arr = np.array(a)
brr = np.ones([112,1])
#print(type(arr))
print(arr)
print(brr)

[889.     879.     887.     894.     887.     902.     888.     902.
 897.     889.     899.     897.     876.     870.     876.     891.
 893.     907.     875.     887.     898.     892.     910.     895.
 910.     914.     914.     905.     896.     903.     901.     886.
 908.     900.     913.     905.     894.     872.     892.     897.
 880.     901.     897.     911.     876.     912.     887.     902.
 918.     909.     908.     894.     898.     875.     879.     882.
 900.     917.     904.     910.     888.     885.     902.     880.
 883.     880.     882.     892.     909.     900.     888.     888.
 869.     902.     877.     887.     910.     904.     919.     892.
 910.     895.     895.     891.     910.     891.     899.     899.
 894.     904.     910.     893.     901.     898.     893.     912.
 901.     890.     883.     888.     872.     888.     895.     891.
 884.     878.     905.     888.3782 910.     909.     923.     918.    ]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

In [95]:
b = arr.reshape(-1,1)
#print(b)
c = np.concatenate((brr, b), axis = 1)
print(c)

[[  1.     889.    ]
 [  1.     879.    ]
 [  1.     887.    ]
 [  1.     894.    ]
 [  1.     887.    ]
 [  1.     902.    ]
 [  1.     888.    ]
 [  1.     902.    ]
 [  1.     897.    ]
 [  1.     889.    ]
 [  1.     899.    ]
 [  1.     897.    ]
 [  1.     876.    ]
 [  1.     870.    ]
 [  1.     876.    ]
 [  1.     891.    ]
 [  1.     893.    ]
 [  1.     907.    ]
 [  1.     875.    ]
 [  1.     887.    ]
 [  1.     898.    ]
 [  1.     892.    ]
 [  1.     910.    ]
 [  1.     895.    ]
 [  1.     910.    ]
 [  1.     914.    ]
 [  1.     914.    ]
 [  1.     905.    ]
 [  1.     896.    ]
 [  1.     903.    ]
 [  1.     901.    ]
 [  1.     886.    ]
 [  1.     908.    ]
 [  1.     900.    ]
 [  1.     913.    ]
 [  1.     905.    ]
 [  1.     894.    ]
 [  1.     872.    ]
 [  1.     892.    ]
 [  1.     897.    ]
 [  1.     880.    ]
 [  1.     901.    ]
 [  1.     897.    ]
 [  1.     911.    ]
 [  1.     876.    ]
 [  1.     912.    ]
 [  1.     887.    ]
 [  1.     902.    ]
 [  1.     918.    ]
 [  1.     909.    ]
 [  1.     908.    ]
 [  1.     894.    ]
 [  1.     898.    ]
 [  1.     875.    ]
 [  1.     879.    ]
 [  1.     882.    ]
 [  1.     900.    ]
 [  1.     917.    ]
 [  1.     904.    ]
 [  1.     910.    ]
 [  1.     888.    ]
 [  1.     885.    ]
 [  1.     902.    ]
 [  1.     880.    ]
 [  1.     883.    ]
 [  1.     880.    ]
 [  1.     882.    ]
 [  1.     892.    ]
 [  1.     909.    ]
 [  1.     900.    ]
 [  1.     888.    ]
 [  1.     888.    ]
 [  1.     869.    ]
 [  1.     902.    ]
 [  1.     877.    ]
 [  1.     887.    ]
 [  1.     910.    ]
 [  1.     904.    ]
 [  1.     919.    ]
 [  1.     892.    ]
 [  1.     910.    ]
 [  1.     895.    ]
 [  1.     895.    ]
 [  1.     891.    ]
 [  1.     910.    ]
 [  1.     891.    ]
 [  1.     899.    ]
 [  1.     899.    ]
 [  1.     894.    ]
 [  1.     904.    ]
 [  1.     910.    ]
 [  1.     893.    ]
 [  1.     901.    ]
 [  1.     898.    ]
 [  1.     893.    ]
 [  1.     912.    ]
 [  1.     901.    ]
 [  1.     890.    ]
 [  1.     883.    ]
 [  1.     888.    ]
 [  1.     872.    ]
 [  1.     888.    ]
 [  1.     895.    ]
 [  1.     891.    ]
 [  1.     884.    ]
 [  1.     878.    ]
 [  1.     905.    ]
 [  1.     888.3782]
 [  1.     910.    ]
 [  1.     909.    ]
 [  1.     923.    ]
 [  1.     918.    ]]